// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARLyfVdIDNW31xD1A6KF0Q2LUabEpXVgA',
    appId: '1:281688650078:web:f3ee3f15798c9c20535fcf',
    messagingSenderId: '281688650078',
    projectId: 'autentificaciones-6f462',
    authDomain: 'autentificaciones-6f462.firebaseapp.com',
    storageBucket: 'autentificaciones-6f462.firebasestorage.app',
    measurementId: 'G-WDHR7QGDLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdDKmceW8tOjch9CXOa28scWCtg8H16kw',
    appId: '1:281688650078:android:70cb83f66de5dea8535fcf',
    messagingSenderId: '281688650078',
    projectId: 'autentificaciones-6f462',
    storageBucket: 'autentificaciones-6f462.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOAW-6f3BenBSlBc2bCcgQLDrcAx_eJBg',
    appId: '1:281688650078:ios:11decd17bf6687a9535fcf',
    messagingSenderId: '281688650078',
    projectId: 'autentificaciones-6f462',
    storageBucket: 'autentificaciones-6f462.firebasestorage.app',
    androidClientId: '281688650078-h3tos23ljb29rgph9ee3viiqfo8tvdnc.apps.googleusercontent.com',
    iosClientId: '281688650078-lo5nobt4i6euivpsh2cp7edn9j1nnbb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.conso2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOAW-6f3BenBSlBc2bCcgQLDrcAx_eJBg',
    appId: '1:281688650078:ios:11decd17bf6687a9535fcf',
    messagingSenderId: '281688650078',
    projectId: 'autentificaciones-6f462',
    storageBucket: 'autentificaciones-6f462.firebasestorage.app',
    androidClientId: '281688650078-h3tos23ljb29rgph9ee3viiqfo8tvdnc.apps.googleusercontent.com',
    iosClientId: '281688650078-lo5nobt4i6euivpsh2cp7edn9j1nnbb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.conso2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARLyfVdIDNW31xD1A6KF0Q2LUabEpXVgA',
    appId: '1:281688650078:web:2e0b5141626e8696535fcf',
    messagingSenderId: '281688650078',
    projectId: 'autentificaciones-6f462',
    authDomain: 'autentificaciones-6f462.firebaseapp.com',
    storageBucket: 'autentificaciones-6f462.firebasestorage.app',
    measurementId: 'G-P13NJT0CFL',
  );
}
